version: "1.0"
info:
  model: int-scaffold
packages:
- name: July16Project
  gitServerName: Rakesh_Github
  gitUrl: https://github.com/Rakeshkumards1997
  gitUsername: Rakeshkumards1997
  gitBranch: main
